osx_image: xcode8.1
language: objective-c
podfile: Example/Podfile

notifications:
  email: false

before_install:
  - pod update --project-directory=Example/

env:
  global:
    - LANG=en_US.UTF-8
    - COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=true

cache:
  - bundler
  - cocoapods

script:
  - set -o pipefail
  - pod install --project-directory=Example
  - xcodebuild -workspace Example/APIKitExt.xcworkspace -scheme "ObjectMapper Sample" CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" | xcpretty -c
  - xcodebuild -workspace Example/APIKitExt.xcworkspace -scheme "Argo Sample" CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" | xcpretty -c
  - xcodebuild -workspace Example/APIKitExt.xcworkspace -scheme "SwiftyJSON Sample" CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" | xcpretty -c
  - xcodebuild -workspace Example/APIKitExt.xcworkspace -scheme "Himotoki Sample" CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" | xcpretty -c
  - xcodebuild build-for-testing test-without-building -workspace Example/APIKitExt.xcworkspace -scheme "Himotoki Sample Tests" -destination 'name=iPhone 7' | xcpretty -c
